logging:
  level: INFO
  loggers:
    org.example: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: task-service
  password: password
  url: jdbc:mysql://mysql1:3306/task-db

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    serverTimezone: Asia/Singapore

  validationQuery: "SELECT 1"